name = 3d_armor_hover
description = Adds hovering animation to 3d_armor character model when having fly privilege
depends = player_api, 3d_armor, skinsdb
optional_depends = simple_skins, clothing
author = Sirrobzeroone
title = 3D Armor Hovering Animation
