name = 3d_armor_hover
description = Add hovering, flying and several other animations to 3d_armor character model.
depends = default, player_api, 3d_armor, skinsdb
author = wks
title = 3D Armor Hovering Animation
