name = 3d_armor_hover
title = 3D Armor Hovering Animation
description = Add hovering, flying and several other animations to 3d_armor character model.
supported_games = minetest_game
depends = default, player_api, 3d_armor, skinsdb
min_minetest_version = 5.13.0
author = wks
